### ISSUE TITLE
bug in mesos.pb.go and other things

### ISSUE THREAD

**Issue by harryzz** [AVENTER-UG/mesos-compose#16]
Hi
First thank you for your work.
I need some simple and customizable mesos scheduler to test containers ( first I used mesos-execute ) and found your mesos-compose app.
There are some problems and/or bugs I found.

1. proto/mesos.pb.go is broken - line 8857 and impossible to use mesos containerizer.
2. You give strange task names (task:project:service) also rewrite framework name and this give me trouble with mesos-dns.
3. I have changed 'Environment' in yaml files to 'map' - this make possible to merge common environment variables in yaml files directly.
4. Added support for value and arguments in Command message. (I need this because there are issue in mesos (they rewrite ENTRYPOINT in docker image) when using mesos containerizer and try to execute command)

diff file attached to commit: b0924ea52afcc1d2353610984d0426be29a62008

P.S. if there strange things or errors in code - sorry this is first time I use Golang.
[b0924ea52afcc1d2353610984d0426be29a62008.diff.txt](https://github.com/AVENTER-UG/mesos-compose/files/12227001/b0924ea52afcc1d2353610984d0426be29a62008.diff.txt)

**Comment by andreaspeters** [comment]
Hi Zahari,

many thanks for your issue and your contribution. 

- 1. good point, I will fix it.
- 2. can you share what kind of problem you got? I'm using mesos-dns too and has no issues with it. 
- 3. can you show me an example what you mean with "merge common env"? 
- 4. :+1: 

I will merge most of the changes into mesos-compose after I test them. :-) 

Again, thank's a lot. :-)

**Comment by harryzz** [comment]
Hi Andreas,

2. As I know and understand mesos-dns map ip to name in this way <task_name>.<framework_name>.mesos. Because you set ':' in task name I got the problem. 
From spec - "DNS names can contain only alphabetic characters (A-Z), numeric characters (0-9), the minus sign (-), and the period (.)" 
And for framework-name you add 'mc' prefix and I don't need this.

3. Example: in service i merge common environment for all services with specific per service. In case of 'list' in yaml file - this is also possible but is too complicated.

```yaml
version: '3.9'

common: &common
  image: io/hci/ozone-common:latest
  restart: no
#"no": never restart the task
#"on-failure": only restart the task if it stopped by a failure
#"unless-stopped": only restart the tasks if it does not stopped
  container_type: mesos
  shell: false
  networks:
    io-local:

defs:
  - env: &env
      OZONE_LIBEXEC_DIR: "/usr/share/ozone/libexec"
      OZONE_CONF_DIR: "/etc/ozone"
      OZONE_HOME: "/usr/share/ozone"
      ANSIBLE_VARS: "core_site:\n  fs.defaultFS: ofs://omservice/\nozone_site:\n  ozone.om.service.ids: omservice\n  ........"

services:
  scm1:
    <<: *common
    environment:
      <<: *env
      ANSIBLE_ROLES: "ozone.ozone_scm"
    hostname: scm1.mycloud.mesos
    arguments: ["ozone","scm"]
    mesos:
      task_name: scm1
    deploy:
#      replicas: "3"
      resources:
        limits:
          cpus: 0.5
          memory: 512
          disk: 512

  om1:
    <<: *common
    environment:
      <<: *env
      ANSIBLE_ROLES: "ozone.ozone_om"
    hostname: om1.mycloud.mesos
    arguments: ["ozone","om"]
    mesos:
      task_name: om1
    deploy:
#      replicas: "3"
      resources:
        limits:
          cpus: 0.5
          memory: 512
          disk: 512
```
regards,
Zahari
